=== jhu502/XWorx/src/main/resources/loadFiles/StandardX01.dtd
<!ELEMENT FlameDataLoad (LoadObject|LoadFile|LoadClass)*>
<!ATTLIST FlameDataLoad loader CDATA #REQUIRED>
<!ATTLIST FlameDataLoad description CDATA "">
<!ELEMENT LoadObject (attr+, link*)>
<!ATTLIST LoadObject type CDATA #REQUIRED>
<!ATTLIST LoadObject where CDATA "">
<!ELEMENT LoadFile ANY>
<!ATTLIST LoadFile filename CDATA #REQUIRED>
<!ELEMENT LoadClass ANY>
<!ATTLIST LoadClass classname CDATA #REQUIRED>
<!ELEMENT attr ANY>
<!ATTLIST attr name CDATA #REQUIRED>
<!ELEMENT link ANY>
<!ATTLIST link type CDATA "">
<!ATTLIST link refer CDATA "">
<!ELEMENT where (attr+)>
<!ATTLIST where type CDATA #REQUIRED>
<!ATTLIST where refer CDATA "">

=== jhu502/XWorx/src/main/resources/loadFiles/xw/action/Action-XPropertyDefinition.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE FlameDataLoad SYSTEM "../../StandardX01.dtd">
<FlameDataLoad loader="xw.action.ActionDataLoader" description="XThingModel ActionMenu">
    <LoadObject type="xw.action.entity.XActionItem" where="type,name">
        <attr name="name">visibility</attr>
        <attr name="type">XPropertyDefinition</attr>
        <attr name="display">Visibility</attr>
        <attr name="style"></attr>
        <attr name="url">thymeleaf/thing/model/propertyVisibilityTab.html</attr>
        <attr name="winType">page</attr>
        <attr name="en_US">Visibility</attr>
        <attr name="zh_CN">可见性</attr>
    </LoadObject>
    <LoadObject type="xw.action.entity.XActionItem" where="type,name">
        <attr name="name">constraints</attr>
        <attr name="type">XPropertyDefinition</attr>
        <attr name="display">Diagram</attr>
        <attr name="style"></attr>
        <attr name="url">thymeleaf/thing/model/propertyConstraintsTab.html</attr>
        <attr name="winType">page</attr>
        <attr name="en_US">Constraints</attr>
        <attr name="zh_CN">约束</attr>
    </LoadObject>
    <LoadObject type="xw.action.entity.XActionModel" where="type,name"><!-- XPropertyDefinition Info Page -->
        <attr name="name">XWX-InfoTabs</attr>
        <attr name="type">XPropertyDefinition</attr>
        <attr name="display">XPropertyDefinition Tabs</attr>
        <attr name="icon">images/flow/flowinst.gif</attr>
        <attr name="style">dropdown-toggle</attr>
        <link type="xw.action.entity.XActionItemLink" refer="left">
            <attr name="sort">10</attr>
            <where type="xw.action.entity.XActionItem" refer="right">
                <attr name="name">visibility</attr>
                <attr name="type">XPropertyDefinition</attr>
            </where>
        </link>
        <link type="xw.action.entity.XActionItemLink" refer="left">
            <attr name="sort">20</attr>
            <where type="xw.action.entity.XActionItem" refer="right">
                <attr name="name">constraints</attr>
                <attr name="type">XPropertyDefinition</attr>
            </where>
        </link>
    </LoadObject>
</FlameDataLoad>

=== jhu502/XWorx/src/main/resources/loadFiles/xw/action/Action-XContext.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE FlameDataLoad SYSTEM "../../StandardX01.dtd">
<FlameDataLoad loader="xw.action.ActionDataLoader" description="Root Model">
	<LoadObject type="xw.action.entity.XActionItem" where="type,name">
		<attr name="name">detail</attr>
		<attr name="type">XLibrary</attr>
		<attr name="display">Detail</attr>
		<attr name="style"></attr>
		<attr name="url">thymeleaf/page/detailsInfo.html</attr>
		<attr name="winType">page</attr>
		<attr name="en_US">Details</attr>
		<attr name="zh_CN">详细信息</attr>
	</LoadObject>
	<LoadObject type="xw.action.entity.XActionItem" where="type,name">
		<attr name="name">folder</attr>
		<attr name="type">XLibrary</attr>
		<attr name="display">Folder</attr>
		<attr name="style"></attr>
		<attr name="url">thymeleaf/context/library/libFoldersTab.html</attr>
		<attr name="winType">page</attr>
		<attr name="en_US">Folder</attr>
		<attr name="zh_CN">文件夹</attr>
	</LoadObject>
	<LoadObject type="xw.action.entity.XActionItem" where="type,name">
		<attr name="name">team</attr>
		<attr name="type">XLibrary</attr>
		<attr name="display">Library Team</attr>
		<attr name="style"></attr>
		<attr name="url">thymeleaf/context/library/libTeamsTab.html</attr>
		<attr name="winType">page</attr>
		<attr name="en_US">Team</attr>
		<attr name="zh_CN">团队</attr>
	</LoadObject>
	<LoadObject type="xw.action.entity.XActionModel" where="type,name"><!-- XPart Info Page Info Tabs -->
		<attr name="name">XWX-InfoTabs</attr>
		<attr name="type">XLibrary</attr>
		<attr name="display">XLibrary Tabs</attr>
		<attr name="icon">images/library.png</attr>
		<attr name="style">dropdown-toggle</attr>
		<link type="xw.action.entity.XActionItemLink" refer="left">
			<attr name="sort">10</attr>
			<where type="xw.action.entity.XActionItem" refer="right">
				<attr name="name">detail</attr>
				<attr name="type">XLibrary</attr>
			</where>
		</link>
		<link type="xw.action.entity.XActionItemLink" refer="left">
			<attr name="sort">20</attr>
			<where type="xw.action.entity.XActionItem" refer="right">
				<attr name="name">folder</attr>
				<attr name="type">XLibrary</attr>
			</where>
		</link>
		<link type="xw.action.entity.XActionItemLink" refer="left">
			<attr name="sort">30</attr>
			<where type="xw.action.entity.XActionItem" refer="right">
				<attr name="name">team</attr>
				<attr name="type">XLibrary</attr>
			</where>
		</link>
	</LoadObject>

	<LoadObject type="xw.action.entity.XActionModel" where="type,name"><!-- XPart Info Page Info Tabs -->
		<attr name="name">XWX-ActionMenu</attr>
		<attr name="type">XLibrary</attr>
		<attr name="display">XLibrary Tabs</attr>
		<attr name="icon">images/library.png</attr>
		<attr name="style">dropdown-toggle</attr>
		<link type="xw.action.entity.XActionItemLink" refer="left">
			<attr name="sort">10</attr>
			<where type="xw.action.entity.XActionItem" refer="right">
				<attr name="name">copy</attr>
				<attr name="type">XObject</attr>
			</where>
		</link>
	</LoadObject>
</FlameDataLoad>

=== jhu502/XWorx/src/main/resources/loadFiles/mes/apl/Action-AssemblyLine.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE FlameDataLoad SYSTEM "../../StandardX01.dtd">
<FlameDataLoad loader="xw.action.ActionDataLoader" description="Production Line">
	<LoadObject type="xw.action.entity.XActionItem" where="type,name">
		<attr name="name">detail</attr>
		<attr name="type">XAssemblyLine</attr>
		<attr name="display">Detail</attr>
		<attr name="style"></attr>
		<attr name="url">thymeleaf/mes/apl/plineDetailsTab.html</attr>
		<attr name="winType">page</attr>
		<attr name="beforeJS"></attr>
		<attr name="afterJS"></attr>
		<attr name="en_US">Details</attr>
		<attr name="zh_CN">详细信息</attr>
	</LoadObject>
	<LoadObject type="xw.action.entity.XActionItem" where="type,name">
		<attr name="name">equipt</attr>
		<attr name="type">XAssemblyLine</attr>
		<attr name="display">Equipment</attr>
		<attr name="style"></attr>
		<attr name="url">thymeleaf/mes/apl/plineEquipmentsTab.html</attr>
		<attr name="winType">page</attr>
		<attr name="beforeJS"></attr>
		<attr name="afterJS"></attr>
		<attr name="en_US">Equipment Management</attr>
		<attr name="zh_CN">设备管理</attr>
	</LoadObject>
	<LoadObject type="xw.action.entity.XActionModel" where="type,name"><!-- XPart Info Page Info Tabs -->
		<attr name="name">XWX-InfoTabs</attr>
		<attr name="type">XAssemblyLine</attr>
		<attr name="display">XAssemblyLine Tabs</attr>
		<attr name="icon">images/part.png</attr>
		<attr name="style">dropdown-toggle</attr>
		<link type="xw.action.entity.XActionItemLink" refer="left">
			<attr name="sort">10</attr>
			<where type="xw.action.entity.XActionItem" refer="right">
				<attr name="name">detail</attr>
				<attr name="type">XAssemblyLine</attr>
			</where>
		</link>
		<link type="xw.action.entity.XActionItemLink" refer="left">
			<attr name="sort">20</attr>
			<where type="xw.action.entity.XActionItem" refer="right">
				<attr name="name">equipt</attr>
				<attr name="type">XAssemblyLine</attr>
			</where>
		</link>
	</LoadObject>

	<LoadObject type="xw.action.entity.XActionItem" where="type,name">
		<attr name="name">newProductLine</attr>
		<attr name="type">XAssemblyLine</attr>
		<attr name="supported_type"></attr>
		<attr name="display">New</attr>
		<attr name="icon">images/newdoc.gif</attr>
		<attr name="style">width:680px;height:380px;padding:5px;</attr>
		<attr name="url">thymeleaf/mes/apl/newProductionLine.html</attr>
		<attr name="processor">mes.apl.processor.CreateProductionLineProcessor</attr>
		<attr name="winType">popup</attr>
		<attr name="beforeJS"></attr>
		<attr name="afterJS"></attr>
		<attr name="en_US">New</attr>
		<attr name="zh_CN">新建</attr>
	</LoadObject>
	<LoadObject type="xw.action.entity.XActionModel" where="type,name"><!-- Navigator Menu -->
		<attr name="name">ProductLineToolbar</attr>
		<attr name="type">XAssemblyLine</attr>
		<attr name="supported_type"></attr>
		<attr name="display">Product Line Toolbar</attr>
		<attr name="icon"></attr>
		<attr name="style"></attr>
		<link type="xw.action.entity.XActionItemLink" refer="left">
			<attr name="sort">10</attr>
			<where type="xw.action.entity.XActionItem" refer="right">
				<attr name="name">newProductLine</attr>
				<attr name="type">XAssemblyLine</attr>
			</where>
		</link>
		<link type="xw.action.entity.XActionItemLink" refer="left">
			<attr name="sort">40</attr>
			<where type="xw.action.entity.XActionItem" refer="right">
				<attr name="name">delete</attr>
				<attr name="type">XObject</attr>
			</where>
		</link>
	</LoadObject>

	<LoadObject type="xw.action.entity.XActionItem" where="type,name">
		<attr name="name">newEquipment</attr>
		<attr name="type">XAssemblyLine</attr>
		<attr name="display">New Equipment</attr>
		<attr name="style"></attr>
		<attr name="icon">images/newEquipt.png</attr>
		<attr name="url">thymeleaf/mes/apl/newEquipment.html</attr>
		<attr name="processor">mes.apl.processor.CreateEquipmentProcessor</attr>
		<attr name="winType">popup</attr>
		<attr name="style">width:680px;height:380px;padding:5px;</attr>
		<attr name="beforeJS"></attr>
		<attr name="afterJS"></attr>
		<attr name="en_US">New</attr>
		<attr name="zh_CN">新建</attr>
	</LoadObject>
	<LoadObject type="xw.action.entity.XActionModel" where="type,name"><!-- XPart Info Page Info Tabs -->
		<attr name="name">PLineEquipt-Toolbar</attr>
		<attr name="type">XAssemblyLine</attr>
		<attr name="display">XAssemblyLine Tabs</attr>
		<attr name="icon">images/part.png</attr>
		<attr name="style">dropdown-toggle</attr>
		<link type="xw.action.entity.XActionItemLink" refer="left">
			<attr name="sort">10</attr>
			<where type="xw.action.entity.XActionItem" refer="right">
				<attr name="name">newEquipment</attr>
				<attr name="type">XAssemblyLine</attr>
			</where>
		</link>
	</LoadObject>

	<LoadObject type="xw.action.entity.XActionItem" where="type,name">
		<attr name="name">equiptInstanceTab</attr>
		<attr name="type">XAssemblyLine</attr>
		<attr name="display">设备</attr>
		<attr name="style"></attr>
		<attr name="url">thymeleaf/mes/equipt/equiptInstanceTab.html</attr>
		<attr name="winType">popup</attr>
		<attr name="beforeJS"></attr>
		<attr name="afterJS"></attr>
		<attr name="en_US">Equiptment</attr>
		<attr name="zh_CN">设备</attr>
	</LoadObject>
	<LoadObject type="xw.action.entity.XActionModel" where="type,name">
		<attr name="name">PLineEquipt-EquiptNavTabs</attr>
		<attr name="type">XAssemblyLine</attr>
		<attr name="display">XAssemblyLine Tabs</attr>
		<attr name="icon">images/part.png</attr>
		<attr name="style">dropdown-toggle</attr>
		<link type="xw.action.entity.XActionItemLink" refer="left">
			<attr name="sort">10</attr>
			<where type="xw.action.entity.XActionItem" refer="right">
				<attr name="name">equiptInstanceTab</attr>
				<attr name="type">XAssemblyLine</attr>
			</where>
		</link>
	</LoadObject>
</FlameDataLoad>

=== jhu502/XWorx/src/main/resources/loadFiles/xw/domain/Basic-XAdminDomain.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE FlameDataLoad SYSTEM "../../StandardX01.dtd">
<FlameDataLoad loader="xw.domain.DomainDataLoader">
	<LoadObject type="xw.domain.entity.XAdminDomain" where="number">
		<attr name="number">/</attr>
		<attr name="name">/</attr>
		<attr name="description">Site Domain</attr>
		<attr name="upperDomain"></attr>
		<attr name="contextRef">XTYPE|xw.context.entity.XSite~MBA|number|SITE</attr>
	</LoadObject>
	<LoadObject type="xw.domain.entity.XAdminDomain" where="number">
		<attr name="number">FLAME</attr>
		<attr name="name">Flame</attr>
		<attr name="description">Organization Domain</attr>
		<attr name="upperDomain">/</attr>
		<attr name="contextRef">XTYPE|xw.context.entity.XOrganization~MBA|number|FLAME</attr>
	</LoadObject>
	<LoadObject type="xw.domain.entity.XAdminDomain" where="number">
		<attr name="number">PDM</attr>
		<attr name="name">PDM</attr>
		<attr name="description">Product Domain</attr>
		<attr name="upperDomain">FLAME</attr>
		<attr name="contextRef">XTYPE|xw.context.entity.XOrganization~MBA|number|FLAME</attr>
	</LoadObject>
	<LoadObject type="xw.domain.entity.XAdminDomain" where="number">
		<attr name="number">MES</attr>
		<attr name="name">MES</attr>
		<attr name="description">Manufacturing Execution Domain</attr>
		<attr name="upperDomain">FLAME</attr>
		<attr name="contextRef">XTYPE|xw.context.entity.XOrganization~MBA|number|FLAME</attr>
	</LoadObject>
	<LoadObject type="xw.domain.entity.XAdminDomain" where="number">
		<attr name="number">PJT</attr>
		<attr name="name">PJT</attr>
		<attr name="description">Project Domain</attr>
		<attr name="upperDomain">FLAME</attr>
		<attr name="contextRef">XTYPE|xw.context.entity.XOrganization~MBA|number|FLAME</attr>
	</LoadObject>
	<LoadObject type="xw.domain.entity.XAdminDomain" where="number">
		<attr name="number">LIB</attr>
		<attr name="name">LIB</attr>
		<attr name="description">General Domain</attr>
		<attr name="upperDomain">FLAME</attr>
		<attr name="contextRef">XTYPE|xw.context.entity.XOrganization~MBA|number|FLAME</attr>
	</LoadObject>
</FlameDataLoad>

=== jhu502/XWorx/src/main/resources/loadFiles/xw/action/Action-XAdminDomain.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE FlameDataLoad SYSTEM "../../../StandardX01.dtd">
<FlameDataLoad loader="xw.action.ActionDataLoader" description="Folder">
	<LoadObject type="xw.action.entity.XActionItem" where="type,name">
		<attr name="name">detail</attr>
		<attr name="type">XAdminDomain</attr>
		<attr name="display">Detail</attr>
		<attr name="style"></attr>
		<attr name="url">thymeleaf/domain/domainDetails.html</attr>
		<attr name="winType">page</attr>
		<attr name="en_US">Details</attr>
		<attr name="zh_CN">详细信息</attr>
	</LoadObject>
	<LoadObject type="xw.action.entity.XActionModel" where="type,name"><!-- XAdminDomain Info Page Info Tabs -->
		<attr name="name">XWX-InfoTabs</attr>
		<attr name="type">XAdminDomain</attr>
		<attr name="display">XAdminDomain Tabs</attr>
		<attr name="icon">images/part.png</attr>
		<attr name="style">dropdown-toggle</attr>
		<link type="xw.action.entity.XActionItemLink" refer="left">
			<attr name="sort">10</attr>
			<where type="xw.action.entity.XActionItem" refer="right">
				<attr name="name">detail</attr>
				<attr name="type">XAdminDomain</attr>
			</where>
		</link>
	</LoadObject>
</FlameDataLoad>

=== jhu502/XWorx/src/main/resources/loadFiles/xw/action/Action-XThingModel.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE FlameDataLoad SYSTEM "../../StandardX01.dtd">
<FlameDataLoad loader="xw.action.ActionDataLoader" description="XThingModel ActionMenu">
    <LoadObject type="xw.action.entity.XActionItem" where="type,name">
        <attr name="name">newThingModel</attr>
        <attr name="type">XThingModel</attr>
        <attr name="display">New</attr>
        <attr name="icon"></attr>
        <attr name="iconCls">icon-add</attr>
        <attr name="style">width:680px;height:480px;padding:5px;</attr>
        <attr name="url">thymeleaf/thing/createThingModel.html</attr>
        <attr name="winType">popup</attr>
        <attr name="en_US">Create Model</attr>
        <attr name="zh_CN">创建</attr>
    </LoadObject>
    <LoadObject type="xw.action.entity.XActionItem" where="type,name">
        <attr name="name">editThingModel</attr>
        <attr name="type">XThingModel</attr>
        <attr name="display">Edit</attr>
        <attr name="icon"></attr>
        <attr name="iconCls">icon-edit</attr>
        <attr name="style">width:680px;height:480px;padding:5px;</attr>
        <attr name="url">thymeleaf/thing/editThingModel.html</attr>
        <attr name="winType">popup</attr>
        <attr name="en_US">Edit Model</attr>
        <attr name="zh_CN">编辑</attr>
    </LoadObject>
    <LoadObject type="xw.action.entity.XActionItem" where="type,name">
        <attr name="name">saveThingModel</attr>
        <attr name="type">XThingModel</attr>
        <attr name="display">Save</attr>
        <attr name="icon"></attr>
        <attr name="style"></attr>
        <attr name="url"></attr>
        <attr name="winType">invoke</attr>
        <attr name="en_US">Save</attr>
        <attr name="zh_CN">保存</attr>
    </LoadObject>
    <LoadObject type="xw.action.entity.XActionItem" where="type,name">
        <attr name="name">deleteThingModel</attr>
        <attr name="type">XThingModel</attr>
        <attr name="display">Delete</attr>
        <attr name="icon"></attr>
        <attr name="iconCls">icon-delete</attr>
        <attr name="style"></attr>
        <attr name="url"></attr>
        <attr name="winType">invoke</attr>
        <attr name="en_US">Delete Model</attr>
        <attr name="zh_CN">删除</attr>
    </LoadObject>
    <LoadObject type="xw.action.entity.XActionModel" where="type,name">
        <attr name="name">ModelTree_RightMenu</attr>
        <attr name="type">XThingModel</attr>
        <attr name="display">Model Tree Right-Click Menu</attr>
        <attr name="style">dropdown-toggle</attr>
        <link type="xw.action.entity.XActionItemLink" refer="left">
            <attr name="sort">10</attr>
            <where type="xw.action.entity.XActionItem" refer="right">
                <attr name="name">newThingModel</attr>
                <attr name="type">XThingModel</attr>
            </where>
        </link>
        <link type="xw.action.entity.XActionItemLink" refer="left">
            <attr name="sort">20</attr>
            <where type="xw.action.entity.XActionItem" refer="right">
                <attr name="name">editThingModel</attr>
                <attr name="type">XThingModel</attr>
            </where>
        </link>
        <link type="xw.action.entity.XActionItemLink" refer="left">
            <attr name="sort">30</attr>
            <where type="xw.action.entity.XActionItem" refer="right">
                <attr name="name">deleteThingModel</attr>
                <attr name="type">XThingModel</attr>
            </where>
        </link>
    </LoadObject>

    <LoadObject type="xw.action.entity.XActionItem" where="type,name">
        <attr name="name">detail</attr>
        <attr name="type">XThingModel</attr>
        <attr name="display">Details</attr>
        <attr name="style"></attr>
        <attr name="url">thymeleaf/thing/model/modelDetailsTab.html</attr>
        <attr name="winType"></attr>
        <attr name="beforeJS"></attr>
        <attr name="afterJS"></attr>
        <attr name="en_US">Details</attr>
        <attr name="zh_CN">详细信息</attr>
    </LoadObject>
    <LoadObject type="xw.action.entity.XActionItem" where="type,name">
        <attr name="name">properties</attr>
        <attr name="type">XThingModel</attr>
        <attr name="display">Properties</attr>
        <attr name="style"></attr>
        <attr name="url">thymeleaf/thing/model/modelPropertiesTab.html</attr>
        <attr name="winType"></attr>
        <attr name="beforeJS"></attr>
        <attr name="afterJS"></attr>
        <attr name="en_US">Properties</attr>
        <attr name="zh_CN">属性</attr>
    </LoadObject>
    <LoadObject type="xw.action.entity.XActionItem" where="type,name">
        <attr name="name">layout</attr>
        <attr name="type">XThingModel</attr>
        <attr name="display">Layout</attr>
        <attr name="style"></attr>
        <attr name="url">thymeleaf/thing/model/modelLayoutTab.html</attr>
        <attr name="winType"></attr>
        <attr name="beforeJS"></attr>
        <attr name="afterJS"></attr>
        <attr name="en_US">Layout</attr>
        <attr name="zh_CN">布局</attr>
    </LoadObject>
    <LoadObject type="xw.action.entity.XActionItem" where="type,name">
        <attr name="name">services</attr>
        <attr name="type">XThingModel</attr>
        <attr name="display">Services</attr>
        <attr name="style"></attr>
        <attr name="url">thymeleaf/thing/model/modelServicesTab.html</attr>
        <attr name="winType"></attr>
        <attr name="beforeJS"></attr>
        <attr name="afterJS"></attr>
        <attr name="en_US">Services</attr>
        <attr name="zh_CN">服务</attr>
    </LoadObject>
    <LoadObject type="xw.action.entity.XActionItem" where="type,name">
        <attr name="name">actions</attr>
        <attr name="type">XThingModel</attr>
        <attr name="display">Actions</attr>
        <attr name="style"></attr>
        <attr name="url">thymeleaf/thing/model/modelActionsTab.html</attr>
        <attr name="winType"></attr>
        <attr name="beforeJS"></attr>
        <attr name="afterJS"></attr>
        <attr name="en_US">Actions</attr>
        <attr name="zh_CN">菜单项</attr>
    </LoadObject>
    <LoadObject type="xw.action.entity.XActionModel" where="type,name">
        <attr name="name">XWX-InfoTabs</attr>
        <attr name="type">XThingModel</attr>
        <attr name="display">ThingModel Info Tabs</attr>
        <attr name="icon">images/navsite.gif</attr>
        <attr name="style">dropdown-toggle</attr>
        <link type="xw.action.entity.XActionItemLink" refer="left">
            <attr name="sort">10</attr>
            <where type="xw.action.entity.XActionItem" refer="right">
                <attr name="name">detail</attr>
                <attr name="type">XThingModel</attr>
            </where>
        </link>
        <link type="xw.action.entity.XActionItemLink" refer="left">
            <attr name="sort">20</attr>
            <where type="xw.action.entity.XActionItem" refer="right">
                <attr name="name">properties</attr>
                <attr name="type">XThingModel</attr>
            </where>
        </link>
        <link type="xw.action.entity.XActionItemLink" refer="left">
            <attr name="sort">30</attr>
            <where type="xw.action.entity.XActionItem" refer="right">
                <attr name="name">layout</attr>
                <attr name="type">XThingModel</attr>
            </where>
        </link>
        <link type="xw.action.entity.XActionItemLink" refer="left">
            <attr name="sort">40</attr>
            <where type="xw.action.entity.XActionItem" refer="right">
                <attr name="name">services</attr>
                <attr name="type">XThingModel</attr>
            </where>
        </link>
        <link type="xw.action.entity.XActionItemLink" refer="left">
            <attr name="sort">99</attr>
            <where type="xw.action.entity.XActionItem" refer="right">
                <attr name="name">actions</attr>
                <attr name="type">XThingModel</attr>
            </where>
        </link>
    </LoadObject>
    
    <LoadObject type="xw.action.entity.XActionModel" where="type,name"><!-- XThingModel Info Page Action Menu -->
        <attr name="name">XWX-ActionMenu</attr>
        <attr name="type">XThingModel</attr>
        <attr name="display">XThingModel Operations</attr>
        <attr name="style">dropdown-toggle</attr>
        <link type="xw.action.entity.XActionItemLink" refer="left">
            <attr name="sort">10</attr>
            <where type="xw.action.entity.XActionItem" refer="right">
                <attr name="name">copy</attr>
                <attr name="type">XObject</attr>
            </where>
        </link>
        <link type="xw.action.entity.XActionItemLink" refer="left">
            <attr name="sort">20</attr>
            <where type="xw.action.entity.XActionItem" refer="right">
                <attr name="name">editThingModel</attr>
                <attr name="type">XThingModel</attr>
            </where>
        </link>
        <link type="xw.action.entity.XActionItemLink" refer="left">
            <attr name="sort">30</attr>
            <where type="xw.action.entity.XActionItem" refer="right">
                <attr name="name">saveThingModel</attr>
                <attr name="type">XThingModel</attr>
            </where>
        </link>
        <link type="xw.action.entity.XActionItemLink" refer="left">
            <attr name="sort">40</attr>
            <where type="xw.action.entity.XActionItem" refer="right">
                <attr name="name">deleteThingModel</attr>
                <attr name="type">XThingModel</attr>
            </where>
        </link>
    </LoadObject>
</FlameDataLoad>

=== jhu502/XWorx/src/main/resources/loadFiles/xw/action/Action-XGroup.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE FlameDataLoad SYSTEM "../../StandardX01.dtd">
<FlameDataLoad loader="xw.action.ActionDataLoader" description="Root Model">
	<LoadObject type="xw.action.entity.XActionItem" where="type,name">
		<attr name="name">detail</attr>
		<attr name="type">XGroup</attr>
		<attr name="display">Detail</attr>
		<attr name="style"></attr>
		<attr name="url">thymeleaf/page/detailsInfo.html</attr>
		<attr name="winType">page</attr>
		<attr name="en_US">Details</attr>
		<attr name="zh_CN">详细信息</attr>
	</LoadObject>
	<LoadObject type="xw.action.entity.XActionModel" where="type,name"><!-- XPart Info Page Info Tabs -->
		<attr name="name">XWX-InfoTabs</attr>
		<attr name="type">XGroup</attr>
		<attr name="display">XGroup Tabs</attr>
		<attr name="icon">images/group.png</attr>
		<attr name="style">dropdown-toggle</attr>
		<link type="xw.action.entity.XActionItemLink" refer="left">
			<attr name="sort">10</attr>
			<where type="xw.action.entity.XActionItem" refer="right">
				<attr name="name">detail</attr>
				<attr name="type">XGroup</attr>
			</where>
		</link>
	</LoadObject>
	<LoadObject type="xw.action.entity.XActionItem" where="type,name">
		<attr name="name">detail</attr>
		<attr name="type">XUser</attr>
		<attr name="display">Detail</attr>
		<attr name="style"></attr>
		<attr name="url">thymeleaf/auths/userDetailsTab.html</attr>
		<attr name="winType">page</attr>
		<attr name="en_US">Details</attr>
		<attr name="zh_CN">详细信息</attr>
	</LoadObject>
	<LoadObject type="xw.action.entity.XActionModel" where="type,name"><!-- XPart Info Page Info Tabs -->
		<attr name="name">XWX-InfoTabs</attr>
		<attr name="type">XUser</attr>
		<attr name="display">XUser Tabs</attr>
		<attr name="icon">images/person.png</attr>
		<attr name="style">dropdown-toggle</attr>
		<link type="xw.action.entity.XActionItemLink" refer="left">
			<attr name="sort">10</attr>
			<where type="xw.action.entity.XActionItem" refer="right">
				<attr name="name">detail</attr>
				<attr name="type">XUser</attr>
			</where>
		</link>
	</LoadObject>
</FlameDataLoad>
