=== jhu502/XWorx/src/main/resources/loadFiles/StandardX01.dtd
<!ELEMENT FlameDataLoad (LoadObject|LoadFile|LoadClass)*>
<!ATTLIST FlameDataLoad loader CDATA #REQUIRED>
<!ATTLIST FlameDataLoad description CDATA "">
<!ELEMENT LoadObject (attr+, link*)>
<!ATTLIST LoadObject type CDATA #REQUIRED>
<!ATTLIST LoadObject where CDATA "">
<!ELEMENT LoadFile ANY>
<!ATTLIST LoadFile filename CDATA #REQUIRED>
<!ELEMENT LoadClass ANY>
<!ATTLIST LoadClass classname CDATA #REQUIRED>
<!ELEMENT attr ANY>
<!ATTLIST attr name CDATA #REQUIRED>
<!ELEMENT link ANY>
<!ATTLIST link type CDATA "">
<!ATTLIST link refer CDATA "">
<!ELEMENT where (attr+)>
<!ATTLIST where type CDATA #REQUIRED>
<!ATTLIST where refer CDATA "">

=== jhu502/XWorx/src/main/resources/loadFiles/xw/action/Action-XFolder.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE FlameDataLoad SYSTEM "../../../StandardX01.dtd">
<FlameDataLoad loader="xw.action.ActionDataLoader" description="Folder">
	<LoadObject type="xw.action.entity.XActionItem" where="type,name">
		<attr name="name">newDocument</attr>
		<attr name="type">XDocument</attr>
		<attr name="supported_type"></attr>
		<attr name="display">New Docuemnt</attr>
		<attr name="icon">images/newdoc.gif</attr>
		<attr name="style">width:680px;height:380px;padding:5px;</attr>
		<attr name="url">thymeleaf/doc/newDocument</attr>
		<attr name="processor">plm.doc.CreateXDocumentProcessor</attr>
		<attr name="winType">popup</attr>
		<attr name="en_US">New Document</attr>
		<attr name="zh_CN">新建文档</attr>
	</LoadObject>
	<LoadObject type="xw.action.entity.XActionItem" where="type,name">
		<attr name="name">newPart</attr>
		<attr name="type">XPart</attr>
		<attr name="supported_type"></attr>
		<attr name="display">New Part</attr>
		<attr name="icon">images/newpart.gif</attr>
		<attr name="style">width:680px;height:580px;padding:5px;</attr>
		<attr name="url">thymeleaf/part/newPart</attr>
		<attr name="processor">plm.part.processor.CreateXPartProcessor</attr>
		<attr name="winType">popup</attr>
		<attr name="en_US">New Part</attr>
		<attr name="zh_CN">新建部件</attr>
	</LoadObject>
	<LoadObject type="xw.action.entity.XActionItem" where="type,name">
		<attr name="name">newFolder</attr>
		<attr name="type">XFolder</attr>
		<attr name="supported_type"></attr>
		<attr name="display">New Folder</attr>
		<attr name="icon">images/newfolder.gif</attr>
		<attr name="style">width:680px;height:380px;padding:5px;</attr>
		<attr name="url">thymeleaf/context/folder/newFolder</attr>
		<attr name="processor">xw.context.processor.CreateFolderProcessor</attr>
		<attr name="winType">popup</attr>
		<attr name="en_US">New Folder</attr>
		<attr name="zh_CN">新建文件夹</attr>
	</LoadObject>

	<!-- Navigator Menu -->
	<LoadObject type="xw.action.entity.XActionModel" where="type,name">
		<attr name="name">folderToolbar</attr>
		<attr name="type">XFolder</attr>
		<attr name="supported_type"></attr>
		<attr name="display">FolderToolbar</attr>
		<attr name="icon"></attr>
		<attr name="style"></attr>
		<link type="xw.action.entity.XActionItemLink" refer="left">
			<attr name="sort">10</attr>
			<where type="xw.action.entity.XActionItem" refer="right">
				<attr name="name">newDocument</attr>
				<attr name="type">XDocument</attr>
			</where>
		</link>
		<link type="xw.action.entity.XActionItemLink" refer="left">
			<attr name="sort">20</attr>
			<where type="xw.action.entity.XActionItem" refer="right">
				<attr name="name">newPart</attr>
				<attr name="type">XPart</attr>
			</where>
		</link>
		<link type="xw.action.entity.XActionItemLink" refer="left">
			<attr name="sort">30</attr>
			<where type="xw.action.entity.XActionItem" refer="right">
				<attr name="name">newFolder</attr>
				<attr name="type">XFolder</attr>
			</where>
		</link>
		<link type="xw.action.entity.XActionItemLink" refer="left">
			<attr name="sort">40</attr>
			<where type="xw.action.entity.XActionItem" refer="right">
				<attr name="name">delete</attr>
				<attr name="type">XObject</attr>
			</where>
		</link>
	</LoadObject>
</FlameDataLoad>

=== jhu502/XWorx/src/main/resources/loadFiles/xw/action/Action-Common.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE FlameDataLoad SYSTEM "../../StandardX01.dtd">
<FlameDataLoad loader="xw.action.ActionDataLoader" description="Folder">
	<LoadObject type="xw.action.entity.XActionItem" where="type,name">
		<attr name="name">delete</attr>
		<attr name="type">XObject</attr>
		<attr name="supported_type"></attr>
		<attr name="display">Delete</attr>
		<attr name="icon">images/delete.png</attr>
		<attr name="style"></attr>
		<attr name="url"></attr>
		<attr name="processor">xw.object.processor.DeleteObjectProcessor</attr>
		<attr name="winType">invoke</attr>
		<attr name="en_US">Delete</attr>
		<attr name="zh_CN">删除</attr>
	</LoadObject>
	<LoadObject type="xw.action.entity.XActionItem" where="type,name">
		<attr name="name">copy</attr>
		<attr name="type">XObject</attr>
		<attr name="display">Copy</attr>
		<attr name="icon">images/copy.gif</attr>
		<attr name="style"></attr>
		<attr name="processor">xw.object.processor.CopyObjectProcessor</attr>
		<attr name="winType">invoke</attr>
		<attr name="en_US">Copy</attr>
		<attr name="zh_CN">复制</attr>
	</LoadObject>
	<LoadObject type="xw.action.entity.XActionItem" where="type,name">
		<attr name="name">paste</attr>
		<attr name="type">XObject</attr>
		<attr name="display">Paste</attr>
		<attr name="icon">images/paste.gif</attr>
		<attr name="style"></attr>
		<attr name="processor">xw.object.processor.PasteObjectProcessor</attr>
		<attr name="winType">invoke</attr>
		<attr name="en_US">Paste</attr>
		<attr name="zh_CN">粘贴</attr>
	</LoadObject>
	<LoadObject type="xw.action.entity.XActionItem" where="type,name">
		<attr name="name">content</attr>
		<attr name="type">XObject</attr>
		<attr name="display">Content</attr>
		<attr name="style"></attr>
		<attr name="url">thymeleaf/content/objectContentTab.html</attr>
		<attr name="winType">page</attr>
		<attr name="en_US">Content</attr>
		<attr name="zh_CN">内容</attr>
	</LoadObject>
</FlameDataLoad>

=== jhu502/XWorx/src/main/resources/loadFiles/xw/auths/Basic-XGroup.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE FlameDataLoad SYSTEM "../../StandardX01.dtd">
<FlameDataLoad loader="xw.auths.XGroupDataLoader" description="XGroup">
	<LoadObject type="xw.auths.entity.XGroup" where="number">
		<attr name="number">XROOT</attr>
		<attr name="name">XROOT</attr>
		<attr name="fullName">XROOT</attr>
		<attr name="englishName">XROOT</attr>
		<attr name="description">System XRoot Group</attr>
		<attr name="tel">15300000000</attr>
		<attr name="fax">000-00000000</attr>
		<attr name="email">xxxx@xworx.cn</attr>
		<attr name="postalCode">000000</attr>
		<attr name="address"></attr>
		<attr name="groupType">SYSTEM</attr>
		<attr name="domain">/</attr>
		<attr name="scope">all</attr>
		<attr name="secretRequired">false</attr>
		<attr name="resourceIds"></attr>
		<attr name="grantTypes">authorization_code,refresh_token,implicit</attr>
		<attr name="redirectUri">http://flame.xworx.cn/XWorx/</attr>
		<attr name="thingModel">XGroup</attr>
	</LoadObject>
	<LoadObject type="xw.auths.entity.XGroup" where="number">
		<attr name="number">Administrators</attr>
		<attr name="name">Administrators</attr>
		<attr name="fullName">Administrators</attr>
		<attr name="englishName">Administrators</attr>
		<attr name="description">System Administrators Group</attr>
		<attr name="tel">15300000000</attr>
		<attr name="fax">000-00000000</attr>
		<attr name="email">xxxx@xworx.com</attr>
		<attr name="postalCode">000000</attr>
		<attr name="address"></attr>
		<attr name="groupType">SYSTEM</attr>
		<attr name="domain">/</attr>
		<attr name="scope">all</attr>
		<attr name="secretRequired">false</attr>
		<attr name="resourceIds"></attr>
		<attr name="grantTypes">authorization_code,refresh_token,password</attr>
		<attr name="redirectUri">http://flame.xworx.cn/XWorx/</attr>
		<attr name="thingModel">XGroup</attr>
		<link type="xw.auths.entity.XGroupGroupLink" refer="right">
			<where type="xw.auths.entity.XGroup" refer="left">
				<attr name="number">XROOT</attr>
			</where>
		</link>
	</LoadObject>
	<LoadObject type="xw.auths.entity.XGroup" where="number">
		<attr name="number">Guests</attr>
		<attr name="name">Guests</attr>
		<attr name="fullName">Guests</attr>
		<attr name="englishName">Guests</attr>
		<attr name="description">System Guests Group</attr>
		<attr name="tel">15300000000</attr>
		<attr name="fax">000-00000000</attr>
		<attr name="email">xxxx@xworx.com</attr>
		<attr name="postalCode">000000</attr>
		<attr name="address"></attr>
		<attr name="groupType">SYSTEM</attr>
		<attr name="domain">/</attr>
		<attr name="scope">all</attr>
		<attr name="secretRequired">false</attr>
		<attr name="resourceIds"></attr>
		<attr name="grantTypes">authorization_code,refresh_token,password</attr>
		<attr name="redirectUri">http://flame.xworx.cn/XWorx/</attr>
		<attr name="thingModel">XGroup</attr>
		<link type="xw.auths.entity.XGroupGroupLink" refer="right">
			<where type="xw.auths.entity.XGroup" refer="left">
				<attr name="number">XROOT</attr>
			</where>
		</link>
	</LoadObject>
</FlameDataLoad>

=== jhu502/XWorx/src/main/resources/loadFiles/com/flame/ModelDataLoadSet.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE FlameDataLoad SYSTEM "../../StandardX01.dtd">
<FlameDataLoad loader="com.flame.loader.FlameDataSetLoader" description="Basic Model">
    <LoadClass classname="com.thing.entity.XThingModel" />
    <LoadClass classname="com.thing.entity.ConnectableEntity" />
    <LoadClass classname="xw.auths.entity.XPrincipal" />
    <LoadClass classname="xw.auths.entity.XGroup" />
    <LoadClass classname="xw.auths.entity.XUser" />
    <LoadClass classname="xw.context.entity.XSite" />
    <LoadClass classname="xw.context.entity.XLibrary" />
    <LoadClass classname="xw.context.entity.XOrganization" />
    <LoadClass classname="xw.flow.entity.XFlowDefinition" />
    <LoadClass classname="xw.flow.entity.XWorkInstance" />
    <LoadClass classname="xw.doc.XDocument" />
    <LoadClass classname="mes.apl.XAssemblyLine" />
    <LoadClass classname="mes.equipt.XEquipment" />
    <LoadClass classname="mes.equipt.XEquiptInstance" />
    <LoadClass classname="mes.equipt.XEquiptParameter" />
    <LoadClass classname="plm.part.XPart" />
    <LoadClass classname="plm.cad.CADDocument" />
</FlameDataLoad>

=== jhu502/XWorx/src/main/resources/loadFiles/xw/auths/Basic-GroupTypeRB.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE FlameDataLoad SYSTEM "../../StandardX01.dtd">
<FlameDataLoad loader="com.flame.localize.EnumeratedLoader" description="EGroupType">
    <LoadObject type="xw.auths.entity.GroupTypeRB" where="name">
        <attr name="name">SYSTEM</attr>
        <attr name="display">System</attr>
        <attr name="en_US">System</attr>
        <attr name="zh_CN">系统</attr>
    </LoadObject>
    <LoadObject type="xw.auths.entity.GroupTypeRB" where="name">
        <attr name="name">CORPORATION</attr>
        <attr name="display">Corporation</attr>
        <attr name="en_US">Corporation</attr>
        <attr name="zh_CN">企业</attr>
    </LoadObject>
    <LoadObject type="xw.auths.entity.GroupTypeRB" where="name">
        <attr name="name">COMPANY</attr>
        <attr name="display">Company</attr>
        <attr name="en_US">Company</attr>
        <attr name="zh_CN">公司</attr>
    </LoadObject>
    <LoadObject type="xw.auths.entity.GroupTypeRB" where="name">
        <attr name="name">DEPARTMENT</attr>
        <attr name="display">Department</attr>
        <attr name="en_US">Department</attr>
        <attr name="zh_CN">部门</attr>
    </LoadObject>
    <LoadObject type="xw.auths.entity.GroupTypeRB" where="name">
        <attr name="name">OFFICE</attr>
        <attr name="display">Office</attr>
        <attr name="en_US">Office</attr>
        <attr name="zh_CN">办公室</attr>
    </LoadObject>
    <LoadObject type="xw.auths.entity.GroupTypeRB" where="name">
        <attr name="name">SECTION</attr>
        <attr name="display">Section</attr>
        <attr name="en_US">Section</attr>
        <attr name="zh_CN">小组</attr>
    </LoadObject>
    <LoadObject type="xw.auths.entity.GroupTypeRB" where="name">
        <attr name="name">NONE</attr>
        <attr name="display">None</attr>
        <attr name="en_US">None</attr>
        <attr name="zh_CN">无</attr>
    </LoadObject>
</FlameDataLoad>

=== jhu502/XWorx/src/main/resources/loadFiles/com/flame/XWorxDataLoader.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE FlameDataLoad SYSTEM "../../StandardX01.dtd">
<FlameDataLoad loader="com.flame.loader.FlameDataSetLoader" description="Basic Data">
    <LoadFile filename="xw/context/Basic-Contexts.xml"/>
    <LoadFile filename="xw/domain/Basic-XAdminDomain.xml"/>
    <LoadFile filename="xw/object/Action-Common.xml"/>
    <LoadFile filename="xw/domain/Action-XAdminDomain.xml"/>
    <LoadFile filename="com/thing/Action-XThingModel.xml"/>
    <LoadFile filename="xw/action/Action-Navigator.xml"/>
    <LoadFile filename="xw/xflow/Action-XWorkflow.xml"/>
    <LoadFile filename="plm/part/Action-XPart.xml"/>
    <LoadFile filename="xw/object/Action-Common.xml"/>
    <LoadFile filename="xw/context/folder/Action-XFolder.xml"/>
    <LoadFile filename="xw/context/Action-XContext.xml"/>
    <LoadFile filename="plm/dynamic/Action-XDynamic.xml"/>
    <LoadFile filename="mes/apl/Action-AssemblyLine.xml"/>
    <LoadFile filename="mes/apl/Action-Equipment.xml"/>
    <LoadFile filename="xw/auths/Basic-XGroup.xml"/>
</FlameDataLoad>

=== jhu502/XWorx/src/main/resources/loadFiles/loadSet/basicLoadSet.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE FlameDataLoad SYSTEM "../../StandardX01.dtd">
<FlameDataLoad loader="com.flame.loader.FlameDataSetLoader" description="basic model load files">
    <LoadFile filename="xw/auths/Basic-GroupTypeRB.xml"/>
    <LoadFile filename="xw/auths/Basic-RoleRB.xml"/>
    <LoadFile filename="xw/context/Basic-LibraryTypeRB.xml"/>

    <LoadFile filename="xw/action/Action-Common.xml"/>
    <LoadFile filename="xw/action/Action-Navigator.xml"/>
    <LoadFile filename="xw/action/Action-XAdminDomain.xml"/>
    <LoadFile filename="xw/action/Action-XContext.xml"/>
    <LoadFile filename="xw/action/Action-XFolder.xml"/>
    <LoadFile filename="xw/action/Action-XGroup.xml"/>
    <LoadFile filename="xw/action/Action-XPropertyDefinition.xml"/>
    <LoadFile filename="xw/action/Action-XServiceDefinition.xml"/>
    <LoadFile filename="xw/action/Action-XThingModel.xml"/>

    <LoadFile filename="xw/auths/Basic-GroupTypeRB.xml"/>
    <LoadFile filename="xw/auths/Basic-RoleRB.xml"/>
    <LoadFile filename="xw/auths/Basic-XGroup.xml"/>
    <LoadFile filename="xw/auths/Basic-XUser.xml"/>

    <LoadFile filename="xw/context/Basic-Contexts.xml"/>
    <LoadFile filename="xw/context/Basic-LibraryTypeRB.xml"/>

    <LoadFile filename="xw/domain/Basic-XAdminDomain.xml"/>
</FlameDataLoad>

=== jhu502/XWorx/src/main/resources/loadFiles/xw/context/Basic-LibraryTypeRB.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE FlameDataLoad SYSTEM "../../StandardX01.dtd">
<FlameDataLoad loader="com.flame.localize.EnumeratedLoader" description="EGroupType">
    <LoadObject type="xw.context.entity.LibraryTypeRB" where="name">
        <attr name="name">PDM</attr>
        <attr name="display">Product Library</attr>
        <attr name="en_US">Product Library</attr>
        <attr name="zh_CN">产品库</attr>
    </LoadObject>
    <LoadObject type="xw.context.entity.LibraryTypeRB" where="name">
        <attr name="name">MES</attr>
        <attr name="display">Manufacturing Execution Library</attr>
        <attr name="en_US">Manufacturing Execution Library</attr>
        <attr name="zh_CN">制造库</attr>
    </LoadObject>
    <LoadObject type="xw.context.entity.LibraryTypeRB" where="name">
        <attr name="name">PJT</attr>
        <attr name="display">Project Library</attr>
        <attr name="en_US">Project Library</attr>
        <attr name="zh_CN">项目库</attr>
    </LoadObject>
    <LoadObject type="xw.context.entity.LibraryTypeRB" where="name">
        <attr name="name">LIB</attr>
        <attr name="display">General Library</attr>
        <attr name="en_US">General Library</attr>
        <attr name="zh_CN">通用库</attr>
    </LoadObject>
</FlameDataLoad>
