=== jhu502/XWorx/src/main/resources/loadFiles/StandardX01.dtd
<!ELEMENT FlameDataLoad (LoadObject|LoadFile|LoadClass)*>
<!ATTLIST FlameDataLoad loader CDATA #REQUIRED>
<!ATTLIST FlameDataLoad description CDATA "">
<!ELEMENT LoadObject (attr+, link*)>
<!ATTLIST LoadObject type CDATA #REQUIRED>
<!ATTLIST LoadObject where CDATA "">
<!ELEMENT LoadFile ANY>
<!ATTLIST LoadFile filename CDATA #REQUIRED>
<!ELEMENT LoadClass ANY>
<!ATTLIST LoadClass classname CDATA #REQUIRED>
<!ELEMENT attr ANY>
<!ATTLIST attr name CDATA #REQUIRED>
<!ELEMENT link ANY>
<!ATTLIST link type CDATA "">
<!ATTLIST link refer CDATA "">
<!ELEMENT where (attr+)>
<!ATTLIST where type CDATA #REQUIRED>
<!ATTLIST where refer CDATA "">

=== jhu502/XWorx/src/main/resources/loadFiles/xw/action/Action-XServiceDefinition.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE FlameDataLoad SYSTEM "../../StandardX01.dtd">
<FlameDataLoad loader="xw.action.ActionDataLoader" description="XThingModel ActionMenu">
    <!-- ThingModel-Service右键菜单 -->
    <LoadObject type="xw.action.entity.XActionItem" where="type,name">
        <attr name="name">newServiceDef</attr>
        <attr name="type">XServiceDefinition</attr>
        <attr name="display">New</attr>
        <attr name="icon">images/add16x16.gif</attr>
        <attr name="iconCls">icon-new</attr>
        <attr name="style">width: 900px; height: 460px; padding: 5px;</attr>
        <attr name="url">thymeleaf/thing/model/newServiceDef.html</attr>
        <attr name="processor">com.thing.processor.CreateServiceDefProcessor</attr>
        <attr name="winType">popup</attr>
        <attr name="supportedType">XThingModel</attr>
        <attr name="en_US">New</attr>
        <attr name="zh_CN">新建</attr>
    </LoadObject>
    <LoadObject type="xw.action.entity.XActionItem" where="type,name">
        <attr name="name">editServiceDef</attr>
        <attr name="type">XServiceDefinition</attr>
        <attr name="display">Edit</attr>
        <attr name="icon"></attr>
        <attr name="iconCls">icon-edit</attr>
        <attr name="style">width: 800px; height: 460px; padding: 5px;</attr>
        <attr name="url">thymeleaf/thing/model/editServiceDef.html</attr>
        <attr name="processor">com.thing.processor.EditServiceDefProcessor</attr>
        <attr name="winType">popup</attr>
        <attr name="en_US">Edit</attr>
        <attr name="zh_CN">编辑</attr>
    </LoadObject>
    <LoadObject type="xw.action.entity.XActionItem" where="type,name">
        <attr name="name">deleteServiceDef</attr>
        <attr name="type">XServiceDefinition</attr>
        <attr name="display">Delete</attr>
        <attr name="icon"></attr>
        <attr name="iconCls">icon-delete</attr>
        <attr name="style"></attr>
        <attr name="url"></attr>
        <attr name="processor">com.thing.processor.DeleteServiceDefProcessor</attr>
        <attr name="windowType">popup</attr>
        <attr name="en_US">Delete</attr>
        <attr name="zh_CN">删除</attr>
    </LoadObject>
    <LoadObject type="xw.action.entity.XActionItem" where="type,name">
        <attr name="name">testServiceDef</attr>
        <attr name="type">XServiceDefinition</attr>
        <attr name="display">Test</attr>
        <attr name="icon"></attr>
        <attr name="iconCls">icon-test</attr>
        <attr name="style">width:900px;height:660px;padding:5px;</attr>
        <attr name="url">thymeleaf/thing/model/testServiceDef.html</attr>
        <attr name="processor">com.thing.processor.TestServiceDefProcessor</attr>
        <attr name="winType">popup</attr>
        <attr name="supportedType">ServiceDefinition</attr>
        <attr name="en_US">Test</attr>
        <attr name="zh_CN">测试</attr>
    </LoadObject>
    <LoadObject type="xw.action.entity.XActionModel" where="type,name">
        <attr name="name">serviceDef_menu</attr>
        <attr name="type">XServiceDefinition</attr>
        <attr name="display">Service右键菜单</attr>
        <attr name="style">dropdown-toggle</attr>
        <link type="xw.action.entity.XActionItemLink" refer="left">
            <attr name="sort">10</attr>
            <where type="xw.action.entity.XActionItem" refer="right">
                <attr name="name">newServiceDef</attr>
                <attr name="type">XServiceDefinition</attr>
            </where>
        </link>
        <link type="xw.action.entity.XActionItemLink" refer="left">
            <attr name="sort">20</attr>
            <where type="xw.action.entity.XActionItem" refer="right">
                <attr name="name">editServiceDef</attr>
                <attr name="type">XServiceDefinition</attr>
            </where>
        </link>
        <link type="xw.action.entity.XActionItemLink" refer="left">
            <attr name="sort">30</attr>
            <where type="xw.action.entity.XActionItem" refer="right">
                <attr name="name">deleteServiceDef</attr>
                <attr name="type">XServiceDefinition</attr>
            </where>
        </link>
        <link type="xw.action.entity.XActionItemLink" refer="left">
            <attr name="sort">40</attr>
            <where type="xw.action.entity.XActionItem" refer="right">
                <attr name="name">testServiceDef</attr>
                <attr name="type">XServiceDefinition</attr>
            </where>
        </link>
    </LoadObject>
</FlameDataLoad>

=== jhu502/XWorx/src/main/resources/loadFiles/mes/apl/Action-Equipment.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE FlameDataLoad SYSTEM "../../StandardX01.dtd">
<FlameDataLoad loader="xw.action.ActionDataLoader" description="Equipment">

	<LoadObject type="xw.action.entity.XActionItem" where="type,name">
		<attr name="name">newEquiptInstance</attr>
		<attr name="type">XEquiptInstance</attr>
		<attr name="display">New</attr>
		<attr name="style"></attr>
		<attr name="icon">images/add16x16.gif</attr>
		<attr name="url">thymeleaf/mes/equipt/newEquiptInstance.html</attr>
		<attr name="processor">mes.apl.processor.CreateEquiptInstanceProcessor</attr>
		<attr name="winType">popup</attr>
		<attr name="style">width:680px;height:380px;padding:5px;</attr>
		<attr name="en_US">Remove</attr>
		<attr name="zh_CN">删除</attr>
	</LoadObject>
	<LoadObject type="xw.action.entity.XActionItem" where="type,name">
		<attr name="name">push2EquiptMachine</attr>
		<attr name="type">XEquiptInstance</attr>
		<attr name="display">推送</attr>
		<attr name="style"></attr>
		<attr name="icon">images/alert.png</attr>
		<attr name="processor">mes.apl.processor.PushEquiptInstanceProcessor</attr>
		<attr name="winType">invoke</attr>
		<attr name="style">width:680px;height:380px;padding:5px;</attr>
		<attr name="beforeJS">return xworx.validateSelect(p, true);</attr>
		<attr name="afterJS"></attr>
		<attr name="en_US">Push Equiptment</attr>
		<attr name="zh_CN">推送设备</attr>
	</LoadObject>
	<LoadObject type="xw.action.entity.XActionModel" where="type,name">
		<attr name="name">EquiptInstance-Toolbar</attr>
		<attr name="type">XEquiptInstance</attr>
		<attr name="display">EquiptInstance Toolbar</attr>
		<attr name="icon">images/part.png</attr>
		<attr name="style">dropdown-toggle</attr>
		<link type="xw.action.entity.XActionItemLink" refer="left">
			<attr name="sort">10</attr>
			<where type="xw.action.entity.XActionItem" refer="right">
				<attr name="name">newEquiptInstance</attr>
				<attr name="type">XEquiptInstance</attr>
			</where>
		</link>
		<link type="xw.action.entity.XActionItemLink" refer="left">
			<attr name="sort">40</attr>
			<where type="xw.action.entity.XActionItem" refer="right">
				<attr name="name">delete</attr>
				<attr name="type">XObject</attr>
			</where>
		</link>
		<link type="xw.action.entity.XActionItemLink" refer="left">
			<attr name="sort">50</attr>
			<where type="xw.action.entity.XActionItem" refer="right">
				<attr name="name">push2EquiptMachine</attr>
				<attr name="type">XEquiptInstance</attr>
			</where>
		</link>
	</LoadObject>

	<LoadObject type="xw.action.entity.XActionItem" where="type,name">
		<attr name="name">newEquiptParameter</attr>
		<attr name="type">XEquiptInstance</attr>
		<attr name="display">新建</attr>
		<attr name="style"></attr>
		<attr name="icon">images/add16x16.gif</attr>
		<attr name="url">thymeleaf/mes/equipt/newEquiptParameter.html</attr>
		<attr name="processor">mes.equipt.processor.CreateEquiptParameterProcessor</attr>
		<attr name="winType">popup</attr>
		<attr name="style">width:680px;height:380px;padding:5px;</attr>
		<attr name="beforeJS"></attr>
		<attr name="afterJS"></attr>
		<attr name="en_US">New</attr>
		<attr name="zh_CN">新建</attr>
	</LoadObject>
	<LoadObject type="xw.action.entity.XActionItem" where="type,name">
		<attr name="name">editEquiptParameter</attr>
		<attr name="type">XEquiptInstance</attr>
		<attr name="display">编辑</attr>
		<attr name="style"></attr>
		<attr name="icon">images/edit.gif</attr>
		<attr name="url">thymeleaf/mes/equipt/editEquiptParameter.html</attr>
		<attr name="processor">mes.equipt.processor.EditEquiptParameterProcessor</attr>
		<attr name="winType">popup</attr>
		<attr name="style">width:680px;height:380px;padding:5px;</attr>
		<attr name="beforeJS">return xworx.validateSelect(p, true);</attr>
		<attr name="afterJS"></attr>
		<attr name="en_US">Edit</attr>
		<attr name="zh_CN">编辑</attr>
	</LoadObject>
	<LoadObject type="xw.action.entity.XActionItem" where="type,name">
		<attr name="name">setParameterValue</attr>
		<attr name="type">XEquiptInstance</attr>
		<attr name="display">设值</attr>
		<attr name="style"></attr>
		<attr name="icon">images/values.png</attr>
		<attr name="url">thymeleaf/mes/equipt/setParameterValue.html</attr>
		<attr name="processor">mes.equipt.processor.SetParameterValueProcessor</attr>
		<attr name="winType">popup</attr>
		<attr name="style">width:680px;height:380px;padding:5px;</attr>
		<attr name="beforeJS">return xworx.validateSelect(p, true);</attr>
		<attr name="afterJS"></attr>
		<attr name="en_US">Set Value</attr>
		<attr name="zh_CN">设置值</attr>
	</LoadObject>
	<LoadObject type="xw.action.entity.XActionItem" where="type,name">
		<attr name="name">push2Thingworx</attr>
		<attr name="type">XEquiptInstance</attr>
		<attr name="display">Push Thingworx</attr>
		<attr name="style"></attr>
		<attr name="icon">images/synchronized.gif</attr>
		<attr name="processor">mes.equipt.processor.SyncEquiptParameterProcessor</attr>
		<attr name="winType">invoke</attr>
		<attr name="beforeJS">return xworx.validateSelect(p, true);</attr>
		<attr name="afterJS"></attr>
		<attr name="en_US">Push Thingworx</attr>
		<attr name="zh_CN">同步Thingworx</attr>
	</LoadObject>
	<LoadObject type="xw.action.entity.XActionItem" where="type,name">
		<attr name="name">delete2Thingworx</attr>
		<attr name="type">XEquiptInstance</attr>
		<attr name="display">同步删除</attr>
		<attr name="style"></attr>
		<attr name="icon">images/sync-delete.png</attr>
		<attr name="processor">mes.equipt.processor.DeleteEquiptParameterProcessor</attr>
		<attr name="winType">invoke</attr>
		<attr name="beforeJS">return xworx.validateSelect(p, true);</attr>
		<attr name="afterJS"></attr>
		<attr name="en_US">Sync Remove</attr>
		<attr name="zh_CN">同步删除</attr>
	</LoadObject>
	<LoadObject type="xw.action.entity.XActionModel" where="type,name">
		<attr name="name">EquiptParameter-Toolbar</attr>
		<attr name="type">XEquiptInstance</attr>
		<attr name="display">EquiptInstance Toolbar</attr>
		<attr name="style">dropdown-toggle</attr>
		<link type="xw.action.entity.XActionItemLink" refer="left">
			<attr name="sort">10</attr>
			<where type="xw.action.entity.XActionItem" refer="right">
				<attr name="name">newEquiptParameter</attr>
				<attr name="type">XEquiptInstance</attr>
			</where>
		</link>
		<link type="xw.action.entity.XActionItemLink" refer="left">
			<attr name="sort">20</attr>
			<where type="xw.action.entity.XActionItem" refer="right">
				<attr name="name">editEquiptParameter</attr>
				<attr name="type">XEquiptInstance</attr>
			</where>
		</link>
		<link type="xw.action.entity.XActionItemLink" refer="left">
			<attr name="sort">30</attr>
			<where type="xw.action.entity.XActionItem" refer="right">
				<attr name="name">setParameterValue</attr>
				<attr name="type">XEquiptInstance</attr>
			</where>
		</link>
		<link type="xw.action.entity.XActionItemLink" refer="left">
			<attr name="sort">40</attr>
			<where type="xw.action.entity.XActionItem" refer="right">
				<attr name="name">delete</attr>
				<attr name="type">XObject</attr>
			</where>
		</link>
		<link type="xw.action.entity.XActionItemLink" refer="left">
			<attr name="sort">50</attr>
			<where type="xw.action.entity.XActionItem" refer="right">
				<attr name="name">delete2Thingworx</attr>
				<attr name="type">XEquiptInstance</attr>
			</where>
		</link>
		<link type="xw.action.entity.XActionItemLink" refer="left">
			<attr name="sort">60</attr>
			<where type="xw.action.entity.XActionItem" refer="right">
				<attr name="name">push2Thingworx</attr>
				<attr name="type">XEquiptInstance</attr>
			</where>
		</link>
	</LoadObject>
</FlameDataLoad>

=== jhu502/XWorx/src/main/resources/loadFiles/xw/action/Action-XWorkflow.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE FlameDataLoad SYSTEM "../../StandardX01.dtd">
<FlameDataLoad loader="xw.action.ActionDataLoader" description="Folder">
    <LoadObject type="xw.action.entity.XActionItem" where="type,name">
        <attr name="name">process</attr>
        <attr name="type">XFlow</attr>
        <attr name="display">Processes</attr>
        <attr name="icon">images/flow/instxflow.gif</attr>
        <attr name="style"></attr>
        <attr name="url">thymeleaf/flow/instance/relatedXWorkInstance.html</attr>
        <attr name="processor"></attr>
        <attr name="winType">page</attr>
        <attr name="en_US">Processes</attr>
        <attr name="zh_CN">进程</attr>
    </LoadObject>

    <LoadObject type="xw.action.entity.XActionItem" where="type,name">
        <attr name="name">detail</attr>
        <attr name="type">XWorkInstance</attr>
        <attr name="display">Details</attr>
        <attr name="style"></attr>
        <attr name="url">thymeleaf/flow/instance/instanceDetailsTab.html</attr>
        <attr name="winType">page</attr>
        <attr name="en_US">Details</attr>
        <attr name="zh_CN">详细信息</attr>
    </LoadObject>
    <LoadObject type="xw.action.entity.XActionItem" where="type,name">
        <attr name="name">diagram</attr>
        <attr name="type">XWorkInstance</attr>
        <attr name="display">Diagram</attr>
        <attr name="style"></attr>
        <attr name="url">thymeleaf/flow/instance/instanceDiagramTab.html</attr>
        <attr name="winType">page</attr>
        <attr name="en_US">Diagram</attr>
        <attr name="zh_CN">流程图</attr>
    </LoadObject>
    <LoadObject type="xw.action.entity.XActionModel" where="type,name"><!-- XPart Info Page Info Tabs -->
        <attr name="name">XWX-InfoTabs</attr>
        <attr name="type">XWorkInstance</attr>
        <attr name="display">XWorkInstance Tabs</attr>
        <attr name="icon">images/flow/flowinst.gif</attr>
        <attr name="style">dropdown-toggle</attr>
        <link type="xw.action.entity.XActionItemLink" refer="left">
            <attr name="sort">10</attr>
            <where type="xw.action.entity.XActionItem" refer="right">
                <attr name="name">detail</attr>
                <attr name="type">XWorkInstance</attr>
            </where>
        </link>
        <link type="xw.action.entity.XActionItemLink" refer="left">
            <attr name="sort">20</attr>
            <where type="xw.action.entity.XActionItem" refer="right">
                <attr name="name">diagram</attr>
                <attr name="type">XWorkInstance</attr>
            </where>
        </link>
    </LoadObject>

    <LoadObject type="xw.action.entity.XActionItem" where="type,name">
        <attr name="name">detail</attr>
        <attr name="type">XFlowDefinition</attr>
        <attr name="display">Detail</attr>
        <attr name="style"></attr>
        <attr name="url">thymeleaf/flow/definition/definitionDetailsTab.html</attr>
        <attr name="winType">page</attr>
        <attr name="en_US">Details</attr>
        <attr name="zh_CN">详细信息</attr>
    </LoadObject>
    <LoadObject type="xw.action.entity.XActionItem" where="type,name">
        <attr name="name">diagram</attr>
        <attr name="type">XFlowDefinition</attr>
        <attr name="display">Diagram</attr>
        <attr name="style"></attr>
        <attr name="url">thymeleaf/flow/definition/definitionDiagramTab.html</attr>
        <attr name="winType">page</attr>
        <attr name="en_US">Diagram</attr>
        <attr name="zh_CN">流程图</attr>
    </LoadObject>
    <LoadObject type="xw.action.entity.XActionModel" where="type,name"><!-- XPart Info Page Info Tabs -->
        <attr name="name">XWX-InfoTabs</attr>
        <attr name="type">XFlowDefinition</attr>
        <attr name="display">XFlowDefinition Tabs</attr>
        <attr name="icon">images/flow/flowdef.gif</attr>
        <attr name="style">dropdown-toggle</attr>
        <link type="xw.action.entity.XActionItemLink" refer="left">
            <attr name="sort">10</attr>
            <where type="xw.action.entity.XActionItem" refer="right">
                <attr name="name">detail</attr>
                <attr name="type">XFlowDefinition</attr>
            </where>
        </link>
        <link type="xw.action.entity.XActionItemLink" refer="left">
            <attr name="sort">20</attr>
            <where type="xw.action.entity.XActionItem" refer="right">
                <attr name="name">diagram</attr>
                <attr name="type">XFlowDefinition</attr>
            </where>
        </link>
    </LoadObject>

    <LoadObject type="xw.action.entity.XActionItem" where="type,name">
        <attr name="name">detail</attr>
        <attr name="type">XWorkItem</attr>
        <attr name="display">Details</attr>
        <attr name="style"></attr>
        <attr name="url">thymeleaf/flow/taskform/workitemTaskForm.html</attr>
        <attr name="winType">page</attr>
        <attr name="en_US">Details</attr>
        <attr name="zh_CN">详细信息</attr>
    </LoadObject>
    <LoadObject type="xw.action.entity.XActionItem" where="type,name">
        <attr name="name">history</attr>
        <attr name="type">XWorkItem</attr>
        <attr name="display">History</attr>
        <attr name="style"></attr>
        <attr name="url">thymeleaf/flow/flowReviewHistory.html</attr>
        <attr name="winType">page</attr>
        <attr name="en_US">History</attr>
        <attr name="zh_CN">历史</attr>
    </LoadObject>
    <LoadObject type="xw.action.entity.XActionModel" where="type,name"><!-- XPart Info Page Info Tabs -->
        <attr name="name">XWX-InfoTabs</attr>
        <attr name="type">XWorkItem</attr>
        <attr name="display">XWorkItem Tabs</attr>
        <attr name="icon">images/flow/usertask.png</attr>
        <attr name="style">dropdown-toggle</attr>
        <link type="xw.action.entity.XActionItemLink" refer="left">
            <attr name="sort">10</attr>
            <where type="xw.action.entity.XActionItem" refer="right">
                <attr name="name">detail</attr>
                <attr name="type">XWorkItem</attr>
            </where>
        </link>
        <link type="xw.action.entity.XActionItemLink" refer="left">
            <attr name="sort">20</attr>
            <where type="xw.action.entity.XActionItem" refer="right">
                <attr name="name">history</attr>
                <attr name="type">XWorkItem</attr>
            </where>
        </link>
    </LoadObject>
</FlameDataLoad>

=== jhu502/XWorx/src/main/resources/loadFiles/xw/context/Basic-Contexts.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE FlameDataLoad SYSTEM "../../StandardX01.dtd">
<FlameDataLoad loader="xw.content.XContextDataLoader" description="XContext">
    <LoadObject type="xw.context.entity.XSite" where="number">
        <attr name="number">SITE</attr>
        <attr name="name">Site</attr>
        <attr name="description">Site</attr>
    </LoadObject>
    <LoadObject type="xw.context.entity.XOrganization" where="number">
        <attr name="number">FLAME</attr>
        <attr name="name">Flame</attr>
        <attr name="description">Flame Organization</attr>
        <attr name="container">SITE</attr>
    </LoadObject>
</FlameDataLoad>

=== jhu502/XWorx/src/main/resources/loadFiles/xw/auths/Basic-RoleRB.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE FlameDataLoad SYSTEM "../../StandardX01.dtd">
<FlameDataLoad loader="xw.auths.loader.RoleRBLoader" description="RoleRB">
    <LoadObject type="xw.auths.entity.RoleRB" where="name">
        <attr name="name">ENGINEER</attr>
        <attr name="display">Engineer</attr>
        <attr name="en_US">Engineer</attr>
        <attr name="zh_CN">工程师</attr>
        <attr name="description">工程技术专业人员，负责基础设施运维和技术支持</attr>
        <attr name="roleType">ROLE</attr>
        <attr name="responsibility"><![CDATA[1. 维护系统基础设施与运行环境; 2. 提供工程技术支持与故障排查; 3. 保障系统稳定性与性能优化; 4. 管理技术工具链与自动化流程; 5. 协助技术方案落地实施;]]></attr>
    </LoadObject>
    <LoadObject type="xw.auths.entity.RoleRB" where="name">
        <attr name="name">LEADER</attr>
        <attr name="display">Leader</attr>
        <attr name="en_US">Leader</attr>
        <attr name="zh_CN">领导</attr>
        <attr name="description">团队管理者，负责团队管理和项目推进</attr>
        <attr name="roleType">ROLE</attr>
        <attr name="responsibility"><![CDATA[1. 制定团队目标与战略; 2. 分配任务和协调资源; 3. 监控项目进度; 4. 管理团队成员; 5. 做出关键决策;]]></attr>
    </LoadObject>
</FlameDataLoad>

=== jhu502/XWorx/src/main/resources/loadFiles/plm/container/Role-PLM.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE FlameDataLoad SYSTEM "../../StandardX01.dtd">
<FlameDataLoad loader="xw.auths.loader.RoleRBLoader" description="RoleRB-Role">
    <LoadObject type="xw.auths.entity.RoleRB" where="name">
        <attr name="name">PRODUCT_MANAGER</attr>
        <attr name="display">Product Manager</attr>
        <attr name="en_US">Product Manager</attr>
        <attr name="zh_CN">产品经理</attr>
        <attr name="description">产品经理</attr>
        <attr name="roleType">ROLE</attr>
        <attr name="responsibility"><![CDATA[负责产品全生命周期管理，包括产品规划与需求定义、产品结构与BOM配置、产品开发流程协调、工程变更与版本控制，确保产品数据的准确性和一致性。]]></attr>
    </LoadObject>
    <LoadObject type="xw.auths.entity.RoleRB" where="name">
        <attr name="name">LIBRARY_MANAGER</attr>
        <attr name="display">Library Manager</attr>
        <attr name="en_US">Library Manager</attr>
        <attr name="zh_CN">存储库经理</attr>
        <attr name="description">存储库经理</attr>
        <attr name="roleType">ROLE</attr>
        <attr name="responsibility"><![CDATA[负责存储库（零部件库/文档库）的分类体系建立与维护，管理标准件和通用件的生命周期、版本与状态，审核存储库数据的规范性与完整性，控制存储库的访问与使用权限。]]></attr>
    </LoadObject>
    <LoadObject type="xw.auths.entity.RoleRB" where="name">
        <attr name="name">GUEST</attr>
        <attr name="display">Guest</attr>
        <attr name="en_US">Guest</attr>
        <attr name="zh_CN">访客</attr>
        <attr name="description">访客</attr>
        <attr name="roleType">ROLE</attr>
        <attr name="responsibility"><![CDATA[访客角色，仅具有对产品数据和文档的只读查看权限，无法进行任何修改、创建或删除操作。]]></attr>
    </LoadObject>
    <LoadObject type="xw.auths.entity.RoleRB" where="name">
        <attr name="name">ADMINISTRATORS</attr>
        <attr name="display">Administrators</attr>
        <attr name="en_US">Administrators</attr>
        <attr name="zh_CN">系统管理员</attr>
        <attr name="description">系统管理员</attr>
        <attr name="roleType">ROLE</attr>
        <attr name="responsibility"><![CDATA[系统管理员角色，拥有系统的最高管理权限，负责用户与角色管理、系统配置、安全策略设置，以及所有产品数据和文档的完全访问控制权限。]]></attr>
    </LoadObject>
</FlameDataLoad>

=== jhu502/XWorx/src/main/resources/loadFiles/xw/auths/Basic-XUser.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE FlameDataLoad SYSTEM "../../StandardX01.dtd">
<FlameDataLoad loader="xw.auths.XUserDataLoader" description="XUser">
	<LoadObject type="xw.auths.entity.XUser" where="number">
		<attr name="number">Administrator</attr>
		<attr name="name">Administrator</attr>
		<attr name="fullName">Administrator</attr>
		<attr name="englishName">Administrator</attr>
		<attr name="description">System Administrator User.</attr>
		<attr name="password">admin</attr>
		<attr name="tel">15386456502</attr>
		<attr name="fax">000-00000000</attr>
		<attr name="email">ftadmin@xworx.cn</attr>
		<attr name="postalCode">000000</attr>
		<attr name="address">湖南省长沙市开福区三一大道</attr>
		<attr name="expired">false</attr>
		<attr name="locked">false</attr>
		<attr name="enabled">true</attr>
		<attr name="thingModel">XUser</attr>
	</LoadObject>
	<LoadObject type="xw.auths.entity.XUser" where="number">
		<attr name="number">Guest</attr>
		<attr name="name">Guest</attr>
		<attr name="fullName">Guest</attr>
		<attr name="englishName">Guest</attr>
		<attr name="description">System Guest User.</attr>
		<attr name="password">guest</attr>
		<attr name="tel">15386456502</attr>
		<attr name="fax">000-00000000</attr>
		<attr name="email">guest@xworx.cn</attr>
		<attr name="postalCode">000000</attr>
		<attr name="address">湖南省长沙市开福区三一大道</attr>
		<attr name="expired">false</attr>
		<attr name="locked">false</attr>
		<attr name="enabled">true</attr>
		<attr name="thingModel">XUser</attr>
	</LoadObject>
</FlameDataLoad>

=== jhu502/XWorx/src/main/resources/loadFiles/plm/part/Basic-ViewRB.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE FlameDataLoad SYSTEM "../../StandardX01.dtd">
<FlameDataLoad loader="com.flame.localize.EnumeratedLoader" description="EGroupType">
    <LoadObject type="plm.part.ViewRB" where="name">
        <attr name="name">Design</attr>
        <attr name="display">Design</attr>
        <attr name="en_US">Design</attr>
        <attr name="zh_CN">设计</attr>
    </LoadObject>
    <LoadObject type="plm.part.ViewRB" where="name">
        <attr name="name">Manufacture</attr>
        <attr name="display">Manufacture</attr>
        <attr name="en_US">Manufacture</attr>
        <attr name="zh_CN">制造</attr>
    </LoadObject>
</FlameDataLoad>
